# This file should be in your Git repo (e.g., in a 'jenkins/' folder)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: petstore-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: petstore
  template:
    metadata:
      labels:
        app: petstore
    spec:
      containers:
      - name: petstore
        image: your-dockerhub-username/petstore:latest # <-- CHANGE THIS
        ports:
        - containerPort: 8080 # Assuming Petstore runs on 8080

---
apiVersion: v1
kind: Service
metadata:
  name: petstore-service
spec:
  type: NodePort
  selector:
    app: petstore
  ports:
  - port: 80       # Port for the service
    targetPort: 8080 # Port on the pod
    nodePort: 30080  # Port on the worker node (matches ALB TG)
